// app/brands/brandData.js

export const brandDetails = {
  borgolj: {
    name: "Бөргөлжин",
    short: "Үндэсний хувцас үйлдвэрлэгч",
    description:
      "Үндэсний хувцасны үйлдвэрлэгч. Гар урлал, соёлын өвийг хадгалсан бүтээгдэхүүн.",
    phone: "99112233",
    email: "info@borgolj.mn",
    address: "Улаанбаатар, Чингэлтэй дүүрэг, 1-р хороо, Жишээ гудамж 12-1",
    workHours: "Да-Ба: 09:00 - 18:00",
    website: "https://borgolj.mn",
  },
  zaya: {
    name: "Заяа",
    short: "Гоёл чимэглэл",
    description: "Гоёл чимэглэл, handmade эдлэлүүд.",
    phone: "99887766",
    email: "contact@zaya.mn",
    address: "УБ, Баянзүрх, 5-р хороо, 15-р байр",
    workHours: "Дав-Баа: 10:00 - 19:00",
    website: "https://zaya.mn",
  },
  munkhjin: {
    name: "Мөнхжин",
    short: "Монгол гутал",
    description: "Монгол гутал, арьсан эдлэл үйлдвэрлэл.",
    phone: "99110011",
    email: "info@munkhjin.mn",
    address: "УБ, Сүхбаатар дүүрэг, 3-р хороо",
    workHours: "Да-Ба: 09:00 - 18:00",
    website: "https://munkhjin.mn",
  },
  uyanga: {
    name: "Уянга",
    short: "Үндэсний дээл",
    description: "Уламжлалт болон модерн загвартай дээл үйлдвэрлэл.",
    phone: "99774455",
    email: "info@uyanga.mn",
    address: "УБ, Хан-Уул дүүрэг, 11-р хороо",
    workHours: "Да-Ня: 10:00 - 20:00",
    website: "https://uyanga.mn",
  },
  nomad: {
    name: "Номад",
    short: "Монгол гэр ба эдлэл",
    description: "Монгол гэр болон уламжлалт гэр ахуйн эдлэлүүдийн худалдаа.",
    phone: "99556677",
    email: "contact@nomad.mn",
    address: "УБ, Сонгинохайрхан, 20-р хороо",
    workHours: "Да-Баа: 08:00 - 17:00",
    website: "https://nomad.mn",
  },
  gobi: {
    name: "Говь",
    short: "Ноолуур эдлэл",
    description: "Ноолуур болон ноосон бүтээгдэхүүн үйлдвэрлэгч.",
    phone: "99001122",
    email: "info@gobi.mn",
    address: "УБ, Чингэлтэй дүүрэг, 4-р хороо",
    workHours: "Дав-Баа: 09:00 - 18:00",
    website: "https://gobi.mn",
  },
};
